#----------------------------------#
#         [Rewards GUI]            #
#         by Sneklingame           #
#----------------------------------#

#Please check the Wiki for more information: https://github.com/sneklingame/Rewards-GUI/wiki/

check-for-updates: true

#Data storage method; YAML or MySQL
storage-method: YAML

host: localhost
port: 3306
database: rewards
table: players
username: root
password: ''

click-message: '&aYou received &l%money% &acoins!'
cooldown-message: '&cYou can claim this reward in &e%days%d %hours%h %minutes%m %seconds%s&f.'

title: '&6&lRewards'
rows: 4
keep-open: true

fill-blank-space:
  enabled: true
  item: STAINED_GLASS_PANE
  data-value: 5


Items:

  daily:
    name: '&a&lDaily Reward'

    type: STORAGE_MINECART
    active-cooldown-type: MINECART
    slot: 12
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l100 &eCoins'
    give-money: 100
    commands:
      - 'say This command is executed by the player'
      - 'console: say This command is executed by the console'
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 86400
    permission: rw.daily
    no-permission-message: "&cYou don't have permission to claim this reward."

  weekly:
    name: '&6&lWeekly Reward'
    type: STORAGE_MINECART
    active-cooldown-type: MINECART
    slot: 13
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l500 &eCoins'
    give-money: 500
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 604800
    permission: rw.weekly
    no-permission-message: "&cYou don't have permission to claim this reward."

  monthly:
    name: '&c&lMonthly Reward'
    type: STORAGE_MINECART
    active-cooldown-type: MINECART
    slot: 14
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l2000 &eCoins'
    give-money: 2000
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 2592000
    permission: rw.monthly
    no-permission-message: "&cYou don't have permission to claim this reward."

  daily_vip:
    name: '&a&lDaily Reward &c&lVIP'
    type: POWERED_MINECART
    active-cooldown-type: MINECART
    slot: 21
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l200 &eCoins'
    give-money: 200
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 86400
    permission: rw.daily.vip
    no-permission-message: "&cYou must have rank &5&lVIP &cto claim this reward."

  weekly_vip:
    name: '&6&lWeekly Reward &c&lVIP'
    type: POWERED_MINECART
    active-cooldown-type: MINECART
    slot: 22
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l1000 &eCoins'
    give-money: 1000
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 604800
    permission: rw.weekly.vip
    no-permission-message: "&cYou must have rank &5&lVIP &cto claim this reward."

  monthly_vip:
    name: '&c&lMonthly Reward &c&lVIP'
    type: POWERED_MINECART
    active-cooldown-type: MINECART
    slot: 23
    lore:
      - ''
      - '&e&l[i]&f Click to get &a&l4000 &eCoins'
    give-money: 4000
    sound: 'LEVEL_UP'
    unavailable-sound: 'VILLAGER_NO'
    cooldown: 2592000
    permission: rw.monthly.vip
    no-permission-message: "&cYou must have rank &5&lVIP &cto claim this reward."
